import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Inter } from "next/font/google";
import Login from "@/components/Login";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/dashborad/Sidebar";
import Dashnav from "@/components/dashborad/Dashnav";
import Dashborad from "@/components/dashborad/Dashborad";


const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--font-inter',
})



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.variable}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}

            >


<div className="">
        <Dashnav/>
    </div>

    <div className="grid grid-cols-5 grid-rows-5 gap-4">
    <div className="row-span-5 hidden md:block"><Sidebar/></div>
    <div className="col-span-4 row-span-5 ">{children}</div>
</div>
        



            </body>
        </html>
    );
}
